import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { glob } from 'glob';

/**
 * Adds AI response as attachment to existing Allure test results
 * @param {string} response - AI response content
 * @param {string} originalPrompt - original error prompt
 * @param {Object} config - AI configuration
 * @param {string} testName - name of the test to attach to
 */
async function addAllureAttachmentToTest(response, originalPrompt, config, testName) {
  if (!config.allure_integration) {
    return;
  }

  try {
    const allureDir = config.allure_results_dir || 'allure-results';
    
    if (!existsSync(allureDir)) {
      console.log(`⚠️  Allure results directory not found: ${allureDir}`);
      return;
    }

    // Ищем существующие результаты тестов
    const testResultFiles = await glob(join(allureDir, '*-result.json'));
    
    if (testResultFiles.length === 0) {
      console.log(`⚠️  No existing test results found in ${allureDir}`);
      return;
    }

    // Находим подходящий тест по имени или берем последний
    let targetTestFile = testResultFiles[testResultFiles.length - 1];
    
    if (testName) {
      const matchingTest = testResultFiles.find(file => {
        try {
          const content = readFileSync(file, 'utf8');
          const testResult = JSON.parse(content);
          return testResult.name && testResult.name.includes(testName);
        } catch {
          return false;
        }
      });
      
      if (matchingTest) {
        targetTestFile = matchingTest;
      }
    }

    // Читаем существующий результат теста
    const testContent = readFileSync(targetTestFile, 'utf8');
    const testResult = JSON.parse(testContent);

    // Создаем уникальный ID для аттачмента
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    const attachmentId = `ai-debug-${timestamp}`;
    
    // Создаем Markdown файл с ответом ИИ
    let markdownContent = `# 🤖 AI Debug Analysis\n\n`;
    markdownContent += `**Generated:** ${new Date().toLocaleString('ru-RU')}\n`;
    markdownContent += `**Model:** ${config.model}\n`;
    markdownContent += `**Test:** ${testResult.name || 'Unknown'}\n\n`;
    markdownContent += `## 🔍 Detected Error\n\n`;
    markdownContent += `\`\`\`\n${originalPrompt}\n\`\`\`\n\n`;
    markdownContent += `## 💡 AI Recommendations\n\n`;
    markdownContent += `${response}\n\n`;
    markdownContent += `---\n*Generated by playwright-ai-auto-debug*`;

    // Сохраняем Markdown файл
    const attachmentPath = join(allureDir, `${attachmentId}.md`);
    writeFileSync(attachmentPath, markdownContent, 'utf8');

    // Добавляем аттачмент к существующему тесту
    if (!testResult.attachments) {
      testResult.attachments = [];
    }

    testResult.attachments.push({
      name: '🤖 AI Debug Analysis',
      source: `${attachmentId}.md`,
      type: 'text/markdown'
    });

    // Добавляем метки для лучшей категоризации
    if (!testResult.labels) {
      testResult.labels = [];
    }

    // Проверяем, нет ли уже метки AI Debug
    const hasAiLabel = testResult.labels.some(label => label.name === 'ai-debug');
    if (!hasAiLabel) {
      testResult.labels.push({
        name: 'ai-debug',
        value: 'enabled'
      });
    }

    // Сохраняем обновленный результат теста
    writeFileSync(targetTestFile, JSON.stringify(testResult, null, 2), 'utf8');

    console.log(`📎 AI response attached to test: ${testResult.name}`);
    console.log(`📄 Attachment file: ${attachmentPath}`);
    
  } catch (error) {
    console.error(`❌ Error adding Allure attachment: ${error.message}`);
  }
}

/**
 * Creates standalone Allure test result for AI analysis
 * @param {string} response - AI response content
 * @param {string} originalPrompt - original error prompt
 * @param {Object} config - AI configuration
 * @param {number} index - file index for naming
 */
function createStandaloneAllureResult(response, originalPrompt, config, index = 0) {
  if (!config.allure_integration) {
    return;
  }

  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    const allureDir = config.allure_results_dir || 'allure-results';
    
    // Создаем директорию если не существует
    if (!existsSync(allureDir)) {
      mkdirSync(allureDir, { recursive: true });
    }

    const attachmentId = `ai-analysis-${timestamp}-${index.toString().padStart(3, '0')}`;
    
    // Создаем Markdown файл
    let markdownContent = `# 🤖 AI Debug Analysis Report\n\n`;
    markdownContent += `**Analysis Date:** ${new Date().toLocaleString('ru-RU')}\n`;
    markdownContent += `**AI Model:** ${config.model}\n`;
    markdownContent += `**Server:** ${config.ai_server}\n`;
    markdownContent += `**File Index:** ${index + 1}\n\n`;
    markdownContent += `## 🔍 Original Error\n\n`;
    markdownContent += `\`\`\`\n${originalPrompt}\n\`\`\`\n\n`;
    markdownContent += `## 💡 AI Solution\n\n`;
    markdownContent += `${response}\n\n`;
    markdownContent += `## 📋 Recommendations\n\n`;
    markdownContent += `1. Review the suggested solution carefully\n`;
    markdownContent += `2. Test the fix in a development environment\n`;
    markdownContent += `3. Update test selectors if needed\n`;
    markdownContent += `4. Consider adding additional wait conditions\n\n`;
    markdownContent += `---\n*Generated automatically by playwright-ai-auto-debug*`;

    // Сохраняем Markdown файл
    const attachmentPath = join(allureDir, `${attachmentId}.md`);
    writeFileSync(attachmentPath, markdownContent, 'utf8');

    // Создаем результат теста для Allure
    const testResult = {
      uuid: `ai-debug-${attachmentId}`,
      name: `🤖 AI Debug Analysis #${index + 1}`,
      fullName: `AI Debug Analysis for error file #${index + 1}`,
      status: 'passed',
      stage: 'finished',
      description: `Automatic AI analysis of Playwright test error with recommended solutions`,
      start: Date.now() - 2000,
      stop: Date.now(),
      attachments: [
        {
          name: '🤖 AI Debug Report',
          source: `${attachmentId}.md`,
          type: 'text/markdown'
        }
      ],
      labels: [
        {
          name: 'suite',
          value: 'AI Debug'
        },
        {
          name: 'feature',
          value: 'Automatic Error Analysis'
        },
        {
          name: 'story',
          value: 'AI-Powered Debugging'
        },
        {
          name: 'severity',
          value: 'normal'
        },
        {
          name: 'ai-debug',
          value: 'enabled'
        }
      ],
      parameters: [
        {
          name: 'AI Model',
          value: config.model
        },
        {
          name: 'API Server',
          value: config.ai_server
        },
        {
          name: 'Error File Index',
          value: (index + 1).toString()
        }
      ]
    };

    // Сохраняем результат теста
    const testResultPath = join(allureDir, `${attachmentId}-result.json`);
    writeFileSync(testResultPath, JSON.stringify(testResult, null, 2), 'utf8');

    console.log(`📊 Standalone Allure result created: ${testResultPath}`);
    console.log(`📎 Attachment: ${attachmentPath}`);
    
  } catch (error) {
    console.error(`❌ Error creating standalone Allure result: ${error.message}`);
  }
}

export { addAllureAttachmentToTest, createStandaloneAllureResult }; 