// lib/sendToAI.js

import fs from 'fs';
import path from 'path';

/**
 * Создает Allure attachment с AI ответом
 * @param {string} aiResponse - ответ AI
 * @param {string} errorContent - содержимое ошибки
 * @param {Object} config - конфигурация
 * @param {number} index - индекс файла
 * @param {string} errorFilePath - путь к файлу ошибки
 */
export async function createAllureAttachment(aiResponse, errorContent, config, index, errorFilePath) {
  try {
    const allureDir = config.allure_results_dir || 'allure-results';
    
    // Создаем директорию если не существует
    if (!fs.existsSync(allureDir)) {
      fs.mkdirSync(allureDir, { recursive: true });
    }
    
    const timestamp = Date.now();
    const attachmentName = `ai-analysis-${timestamp}-${index}.md`;
    const attachmentPath = path.join(allureDir, attachmentName);
    
    const content = createAllureAttachmentContent(aiResponse, errorContent, errorFilePath);
    
    fs.writeFileSync(attachmentPath, content, 'utf-8');
    
    console.log(`📎 Created Allure attachment: ${attachmentName}`);
    
  } catch (error) {
    console.error(`❌ Failed to create Allure attachment: ${error.message}`);
  }
}

/**
 * Сохраняет AI ответ в markdown файл
 * @param {string} aiResponse - ответ AI
 * @param {string} errorContent - содержимое ошибки
 * @param {Object} config - конфигурация
 * @param {number} index - индекс файла
 */
export function saveResponseToMarkdown(aiResponse, errorContent, config, index) {
  try {
    const outputDir = config.ai_responses_dir || 'ai-responses';
    
    // Создаем директорию если не существует
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    
    const timestamp = Date.now();
    const filename = config.ai_response_filename_template 
      ? config.ai_response_filename_template
          .replace('{timestamp}', timestamp)
          .replace('{index}', index)
      : `ai-response-${timestamp}-${index}.md`;
    
    const filePath = path.join(outputDir, filename);
    
    const content = createMarkdownContent(aiResponse, errorContent, config);
    
    fs.writeFileSync(filePath, content, 'utf-8');
    
    console.log(`📄 Saved AI response: ${filename}`);
    
  } catch (error) {
    console.error(`❌ Failed to save markdown response: ${error.message}`);
  }
}

/**
 * Создает содержимое Allure attachment
 */
function createAllureAttachmentContent(aiResponse, errorContent, errorFilePath) {
  const timestamp = new Date().toISOString();
  
  return `# 🤖 AI Test Analysis

## 📊 Analysis Details
- **Timestamp:** ${timestamp}
- **Error File:** ${errorFilePath || 'Unknown'}
- **Analysis Type:** Automated AI Debug

## 🔍 Detected Error
\`\`\`
${errorContent || 'No error content available'}
\`\`\`

## 💡 AI Recommended Solution
${aiResponse || 'No AI response available'}

---
*Generated by playwright-ai-auto-debug*
`;
}

/**
 * Создает markdown содержимое
 */
function createMarkdownContent(aiResponse, errorContent, config) {
  const timestamp = new Date().toISOString();
  
  let content = `# 🤖 AI Analysis Report

**Generated:** ${timestamp}
**Configuration:** ${config.model || 'Unknown model'}

## 🔍 Error Analysis
\`\`\`
${errorContent || 'No error content'}
\`\`\`

## 💡 AI Solution
${aiResponse || 'No AI response'}

`;

  // Добавляем метаданные если включено
  if (config.include_metadata) {
    content += `
## 📋 Metadata
- **API Server:** ${config.ai_server || 'Not specified'}
- **Model:** ${config.model || 'Not specified'}
- **Max Tokens:** ${config.max_tokens || 'Not specified'}
- **Temperature:** ${config.temperature || 'Not specified'}
- **Allure Integration:** ${config.allure_integration ? 'Enabled' : 'Disabled'}
- **MCP Integration:** ${config.mcp_integration ? 'Enabled' : 'Disabled'}
`;
  }

  content += '\n---\n*Generated by playwright-ai-auto-debug*\n';
  
  return content;
}

/**
 * Legacy функция для обратной совместимости
 */
export async function sendToAI(prompt, config, domSnapshot) {
  // Перенаправляем на legacy реализацию
  const { sendToAI: legacySendToAI } = await import('../src/infrastructure/legacy/LegacySendToAI.js');
  return await legacySendToAI(prompt, config, domSnapshot);
}
